title: Darrel Hanich # your name (or website title) here
logo: "/images/Personal Picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst
  <br><br>
  Dad, Husband, Cyclist, Data Analyzer
  <br><br>
  <a href="https://www.linkedin.com/in/darrel-hanich/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/darrel.hanich/vizzes/">View My Tableau Profile</a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
